on: [pull_request]

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: copy-labels
        uses: microdataxyz/copy-issue-labels@v1.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          custom-keywords: |
            solves
            implements
